# Generated by Django 5.2.8 on 2025-11-08 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetoPesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('concluido', 'Concluído'), ('pausado', 'Pausado')], default='ativo', max_length=10)),
                ('alunos', models.ManyToManyField(blank=True, related_name='projetos_inscritos', to=settings.AUTH_USER_MODEL)),
                ('orientador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos_orientados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
